parameters:
  product_entity: 'ItcKidsBundle:Product\KidsProduct'
  product_class: 'Itc\KidsBundle\Entity\Product\KidsProduct'
  product_type: 'Itc\KidsBundle\Form\Product\KidsProductType'
  group_entity: 'ItcKidsBundle:Product\KidsProductGroup'
  group_class: 'Itc\KidsBundle\Entity\Product\KidsProductGroup'